### ISSUE TITLE
Create A Main Menu

### ISSUE THREAD

**Issue by MangoDragonHub** [MangoDragonHub/BasketBallProject#13]
2D Menu + 2D Background
3D Menu + 2D Background
2D Menu + 3D Background
3D Menu + 3D Background
(Ask Team for Ideal solution + Gather References)

Main Game Modes (for Playable Prototype 2)
- Play Game
- Options
- Exit to Desktop

**This menu must be controllable by both Controller and Keyboard Input**

**Comment by BuYKMan** [comment]
do you want to help ?
i would like to help
can you e-mail me

**Comment by MangoDragonHub** [comment]
My apologies, but this project is only for people who currently go to my University and for source control.

**Comment by MangoDragonHub** [comment]
Removing the Options button temporarily. 
Play button should be labeled as "Enter Test Map"
Exit to Desktop should be the same.

**Comment by MangoDragonHub** [comment]
Dummy menu is finished. Still need to discuss how the final menu will look.

**Comment by BuYKMan** [comment]
what kind of thing can i do ?
Let's talk on discord?

16 Kas 2022 Çar 04:30 tarihinde MangoDragonHub ***@***.***>
şunu yazdı:
