### ISSUE TITLE
Create a Pause Menu

### ISSUE THREAD

**Issue by MangoDragonHub** [MangoDragonHub/BasketBallProject#14]
This is the menu that appears when one of the players stops the game.

The Following options that should be:
- Continue
- Restart
- Controls
- Quit to Menu

**Comment by BuYKMan** [comment]
do you want to help ? 
i would like to help 
can you e-mail me

**Comment by MangoDragonHub** [comment]
Will revise Pause Menu with Restart and Controls options at a later date. Continue and Quit to Menu will be available.
