### ISSUE TITLE
Animations for Build 4 - Basic 

### ISSUE THREAD

**Issue by MangoDragonHub** [MangoDragonHub/BasketBallProject#23]
- [x] Idle
- [x] Idle - Waiting State if Player isn't doing anything after X amount of seconds
- [x] Running
- [x] Shooting the Ball
- [x] Jumping
- [x] Slam Dunk

**Comment by Briantheboy** [comment]
I can't tick the boxes.

**Comment by Briantheboy** [comment]
Running, Shooting, and Jumping are done...for now

**Comment by Briantheboy** [comment]
I still can't checkmark stuff. Please check off slam dunks.

**Comment by MangoDragonHub** [comment]
All current animations are complete. Closing Issue.
